### ISSUE TITLE
Roadmap towards 1.0

### ISSUE THREAD

**Issue by stellasia** [stellasia/neomap#95]
Work in progress... Please comment on this issue if you have any input regarding the roadmap.

# Roadmap towards release 1.0

## Features

- Relationships visualization (#15) (WIP by @nikita03565)
- Database selection (#86)
- Dataset definition separated from rendering (#94 ) : to be decided, this imply a huge refactoring (also impact the UI)

## UI

- Hide/collapse the side bar  (or the map in edition mode ?) (#84)
- Add rich popups (#67)

## Code quality

- Merge work by @jodom from `master_dev` to `master` (Assigned to: @stellasia )
- Enhance tests (from the initial configuration by jodom) (Assigned to: @stellasia )
- Add project linter

## Contributions

- Write clear contribution guidelines (Assigned to: @stellasia )
    - Setup a review process with quick feedback loop

**Comment by stellasia** [comment]
Hey @nikita03565 , potentially found a couple of issues fixed by https://github.com/stellasia/neomap/pull/106, if you want to check that this is consistent with your changes. 

Apart from that, I think we are ready. Still to do:
- [ ] Check https://github.com/stellasia/neomap/pull/106 and merge if OK
- [ ] Build new release (npm run build)
- [ ] Create 0.6.0 tag on github and upload package
- [ ] Publish new release to NPM

Do you want to give it a try?
